spring:
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true # 允许携带认证信息
            allowedOrigins: "*"    # 允许跨域的源(网站域名/ip)，设置*为全部
            allowedHeaders: "*"    # 允许跨域请求里的head字段，设置*为全部
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS   # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
      discovery:
        locator:
          enabled: true #启用基于服务发现的路由定位
          lowerCaseServiceId: true #服务名称大小写忽略
eureka:
  instance:
    preferIpAddress: true #将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server）
    instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20001/eureka/
    registerWithEureka: true #服务注册 false 自己不注册到服务中心
    fetchRegistry: true #服务发现  表示自己端就是注册中心 我的职责就是维护服务实例 false  自己不获取注册信息

management:
  endpoints:
    web:
      exposure:
        include: '*' #开放所有页面节点  默认只开启了health、info两个节点
  endpoint:
    health:
      show-details: always

server:
  port: 10001
